#Requires -Version 5.1
<#
.SYNOPSIS
    Generate a Windows Sandbox configuration that isolates an AEC program.

.DESCRIPTION
    A PowerShell job is not a security boundary, so this script does not wrap
    the command in one. Instead it writes a .wsb configuration for Windows
    Sandbox: a Hyper-V based virtual machine with a clean Windows image. Only
    the repository is mapped in, as a read-only folder, so the program cannot
    reach the host filesystem, the host network adapter, or host credentials.

    Generate the configuration and start the VM:

        pwsh -File scripts/sandbox-windows.ps1 -EmitConfig
        WindowsSandbox.exe aec-sandbox.wsb

    Then, inside the VM:

        cd C:\aec
        cargo build --release -p aec-cli
        .\target\release\aec.exe check .\examples\nominal.aec

    Windows Sandbox requires Windows 11, or Windows 10 Pro/Enterprise/Education
    with virtualization enabled. On other editions use AppContainer or a WDAC
    policy instead; see SECURITY.md.
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string]$Command,

    [switch]$EmitConfig,

    [string]$ConfigFile,

    [switch]$DisableNetworking
)

$ErrorActionPreference = "Stop"

$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path

if (-not $EmitConfig) {
    Write-Error "Refusing to run '$Command' in-process: a PowerShell job is not an isolation boundary. Re-run with -EmitConfig, then start the generated .wsb in Windows Sandbox."
    exit 2
}

if (-not $ConfigFile) {
    $ConfigFile = Join-Path $root "aec-sandbox.wsb"
}

$escapedRoot = $root.Replace('\', '\\')
$escapedCommand = if ($Command) {
    "  <!-- Command: $([System.Security.SecurityElement]::Escape($Command)) -->`r`n"
} else {
    ""
}
$networking = if ($DisableNetworking) { "Disable" } else { "Default" }

$config = @"
<Configuration>
  <!-- Generated by scripts/sandbox-windows.ps1. Run inside Windows Sandbox. -->
$escapedCommand  <VGpu>Disable</VGpu>
  <Networking>$networking</Networking>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>$escapedRoot</HostFolder>
      <SandboxFolder>C:\aec</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <LogonType>User</LogonType>
  <MappedNetDrives>Disable</MappedNetDrives>
  <CopyProtectedData>Disable</CopyProtectedData>
</Configuration>
"@

[System.IO.File]::WriteAllText($ConfigFile, $config, [System.Text.UTF8Encoding]::new($false))

Write-Output "wrote $ConfigFile"
Write-Output "mount:  $root -> C:\aec (read-only)"
Write-Output "next:   WindowsSandbox.exe `"$ConfigFile`""
