[package]
name = "aec-ast"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "AST definitions for the AEC language"

[dependencies]
uuid.workspace = true
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
